# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookManagement' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'IQKeyboardManagerSwift', '~> 6.3.0'

  # Pods for BookManagement

  target 'BookManagementTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BookManagementUITests' do
    # Pods for testing
  end

end
